title: Web Projects
author: joquendo
email: james4public@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A collection of projects, both professional and experimental.
theme: minima

# social links
twitter_username: devtechone # DO NOT include the @ character, or else the build will fail!
github_username:  joquendo # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
